AUGMENTATION: True
IMAGE_SIZE: [224,224,3] #as per VGG 16 model 
BATCH_SIZE: 16
INCLUDE_TOP: False #we are using the pre trained model , so we have to train the custom model only 
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
